apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-gateway-deployment
  labels:
    app: express-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-gateway
  template:
    metadata:
      labels:
        app: express-gateway
    spec:
      containers:
        - name: express-gateway
          image : express-gateway-image:latest
          imagePullPolicy: Never #Only necessary for local, since it will try to pull from dockerhub if this isn't set
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: express-gateway-service
spec:
  type: LoadBalancer
  selector:
    app: express-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080